api/urls.py
from django.urls import path
from . import views

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path("", views.getRoutes),
    # path("hearts/", views.getHeart, name="heart"),
    path("heart/", views.HeartDetail.as_view(), name="heart-details"),
    path("users/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("users/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
]

devsearch/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
    path("report", include("app.urls")),
    path("api/", include("api.urls")),
    path(
        "reset_password/",
        auth_views.PasswordResetView.as_view(template_name="reset_password.html"),
        name="reset_password",
    ),
    path(
        "reset_password_sent/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="reset_password_sent.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="reset_password_complete.html"
        ),
        name="password_reset_complete",
    ),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("login/", views.loginUser, name="login"),
    path("logout/", views.logoutUser, name="logout"),
    path("register/", views.registerUser, name="register"),
    path("", views.userAccount, name="account"),
    path("edit-details/", views.ediDetail, name="edit-details"),
    path("check-heart/", views.checkHeart, name="check-heart"),
    path("edit-account/", views.editAccount, name="edit-account"),
    path("inbox/", views.inbox, name="inbox"),
    path("message/<str:pk>/", views.viewMessage, name="message"),
    path("create-message/<str:pk>/", views.createMessage, name="create-message"),
]

users/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_delete, post_save
from django.dispatch import receiver

# Create your models here.


CP_CHOICES = (
    (0, "Typical Angina"),
    (1, "Atypical Angina"),
    (2, "Non-Anginal Pain"),
    (3, "Asymptomatic"),
)

FBS_CHOICES = (
    (0, "Fasting Blood Sugar < 120 mg/dl"),
    (1, "Fasting Blood Sugar > 120 mg/dl"),
)

RESTECG_CHOICES = (
    (0, "Normal"),
    (1, "Having ST-T wave abnormality"),
    (2, "Showing probable or definite left ventricular hypertrophy"),
)

EXANG_CHOICES = (
    (0, "No"),
    (1, "Yes"),
)

SEX_CHOICES = (
    (0, "Female"),
    (1, "Male"),
)

SLOPE_CHOICES = (
    (0, "Upsloping"),
    (1, "Flat"),
    (2, "Downsloping"),
)

THAL_CHOICES = (
    (1, "Normal"),
    (2, "Fixed Defect"),
    (3, "Reversible Defect"),
)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=500, blank=True, null=True)
    username = models.CharField(max_length=200, blank=True, null=True)
    location = models.CharField(max_length=200, blank=True, null=True)

    profile_image = models.ImageField(
        null=True,
        blank=True,
        upload_to="profiles/",
        default="profiles/user-default.png",
    )

    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
    )

    def __str__(self):
        return str(self.username)

    class Meta:
        ordering = ["created"]

    @property
    def imageURL(self):
        try:
            url = self.profile_image.url
        except:
            url = ""
        return url


class Heart(models.Model):
    owner = models.OneToOneField(
        Profile, on_delete=models.CASCADE, null=True, blank=True
    )

    age = models.IntegerField(default=0, null=True, blank=True)
    sex = models.IntegerField(choices=SEX_CHOICES, default=0)
    cp = models.IntegerField(choices=CP_CHOICES, default=1)
    trestbps = models.IntegerField(default=0, null=True, blank=True)
    chol = models.IntegerField(default=0, null=True, blank=True)
    fbs = models.IntegerField(choices=FBS_CHOICES, default=0)
    restecg = models.IntegerField(choices=RESTECG_CHOICES, default=0)
    thalach = models.IntegerField(default=0, null=True, blank=True)
    exang = models.IntegerField(choices=EXANG_CHOICES, default=0)
    oldpeak = models.FloatField(default=0)
    slope = models.IntegerField(choices=SLOPE_CHOICES, default=0)
    ca = models.IntegerField(
        default=0,
        null=True,
        blank=True,
        help_text="Major vessels (0-3) colored by flourosopy",
    )
    thal = models.IntegerField(choices=THAL_CHOICES, default=0)

    result1 = models.IntegerField(default=0, null=True, blank=True)
    result2 = models.IntegerField(default=0, null=True, blank=True)
    result3 = models.IntegerField(default=0, null=True, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
    )

    def __str__(self):
        return str(self.owner)


class Message(models.Model):
    sender = models.ForeignKey(
        Profile, on_delete=models.SET_NULL, null=True, blank=True
    )
    recipient = models.ForeignKey(
        Profile,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="messages",
    )
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    subject = models.CharField(max_length=200, null=True, blank=True)
    body = models.TextField()
    is_read = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
    )

    def __str__(self):
        return self.subject

    class Meta:
        ordering = ["is_read", "-created"]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm

from .models import Heart, Message, Profile


class HeartForm(ModelForm):
    class Meta:
        model = Heart
        fields = [
            "age",
            "sex",
            "cp",
            "trestbps",
            "chol",
            "fbs",
            "restecg",
            "thalach",
            "exang",
            "oldpeak",
            "slope",
            "ca",
            "thal",
        ]
        labels = {
            "age": "Age",
            "sex": "Sex",
            "cp": "Chest Pain Type(cp)",
            "trestbps": "Resting Blood Pressure(rbp)",
            "chol": "Serum Cholestoral(chol)",
            "fbs": "Fasting Blood Sugar(fbs)",
            "restecg": "Resting ElectroCardioGraphic(restecg)",
            "thalach": "Maximum Heart Rate Achieved(thalach)",
            "exang": "Exercise Enduced Angina(exang)",
            "oldpeak": "ST depression induced(oldpeak)",
            "slope": "the slope of the peak exercise ST segment(slope)",
            "ca": "number of major vessels(ca)",  # number of major vessels (0-3) colored by flourosopy
            "thal": "Thalessemia(thal)",
        }

    def __init__(self, *args, **kwargs):
        super(HeartForm, self).__init__(*args, **kwargs)
        self.fields["oldpeak"] = forms.FloatField(max_value=100, min_value=0)
        self.fields["ca"] = forms.FloatField(max_value=3, min_value=0)
        self.fields["age"] = forms.FloatField(max_value=150, min_value=0)

        for name, field in self.fields.items():
            field.widget.attrs.update({"class": "input"})


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["first_name", "email", "username", "password1", "password2"]
        labels = {
            "first_name": "Name",
        }

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({"class": "input"})


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = [
            "name",
            "email",
            "username",
            "location",
            "profile_image",
        ]

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({"class": "input"})


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ["name", "email", "subject", "body"]

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({"class": "input"})

users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Q
from django.dispatch.dispatcher import receiver
from django.shortcuts import redirect, render
from django.urls import conf

from .forms import CustomUserCreationForm, HeartForm, MessageForm, ProfileForm
from .models import Heart, Message, Profile

import numpy as np
import pickle


def loginUser(request):
    page = "login"

    if request.user.is_authenticated:
        return redirect("account")

    if request.method == "POST":
        username = request.POST["username"].lower()
        password = request.POST["password"]

        try:
            user = User.objects.get(username=username)
        except:

            messages.error(request, "Username does not exist")

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect(request.GET["next"] if "next" in request.GET else "account")

        else:
            messages.error(request, "Username OR password is incorrect")

    return render(request, "users/login_register.html")


def logoutUser(request):
    logout(request)
    messages.info(request, "User was logged out!")
    return redirect("login")


def registerUser(request):
    page = "register"
    form = CustomUserCreationForm()

    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()

            messages.success(request, "User account was created!")

            login(request, user)
            return redirect("edit-account")

        else:
            messages.success(request, "An error has occurred during registration")

    context = {"page": page, "form": form}
    return render(request, "users/login_register.html", context)


def userProfile(request, pk):
    profile = Profile.objects.get(id=pk)

    topSkills = profile.skill_set.exclude(description__exact="")
    otherSkills = profile.skill_set.filter(description="")

    context = {"profile": profile, "topSkills": topSkills, "otherSkills": otherSkills}
    return render(request, "users/user-profile.html", context)


@login_required(login_url="login")
def userAccount(request):
    profile = request.user.profile
    heart = Heart.objects.get(owner=profile)
    form = HeartForm(instance=heart)

    context = {"profile": profile, "form": form, "heart": heart}
    return render(request, "users/account.html", context)


@login_required(login_url="login")
def editAccount(request):
    profile = request.user.profile
    form = ProfileForm(instance=profile)

    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()

            return redirect("account")

    context = {"form": form}
    return render(request, "users/profile_form.html", context)


@login_required(login_url="login")
def inbox(request):
    profile = request.user.profile
    messageRequests = profile.messages.all()
    unreadCount = messageRequests.filter(is_read=False).count()
    context = {"messageRequests": messageRequests, "unreadCount": unreadCount}
    return render(request, "users/inbox.html", context)


@login_required(login_url="login")
def viewMessage(request, pk):
    profile = request.user.profile
    message = profile.messages.get(id=pk)
    if message.is_read == False:
        message.is_read = True
        message.save()
    context = {"message": message}
    return render(request, "users/message.html", context)


def createMessage(request, pk):

    try:
        sender = request.user.profile
    except:
        sender = None

    if request.method == "POST":
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.sender = sender
            message.recipient = recipient

            if sender:
                message.name = sender.name
                message.email = sender.email
            message.save()

            messages.success(request, "Your message was successfully sent!")
            return redirect("user-profile", pk=recipient.id)

    context = {"recipient": recipient, "form": form}
    return render(request, "users/message_form.html", context)


@login_required(login_url="login")
def ediDetail(request):
    profile = request.user.profile
    heart = Heart.objects.get(owner=profile)

    form = HeartForm(instance=heart)
    if request.method == "POST":
        form = HeartForm(request.POST, instance=heart)

        if form.is_valid():
            heart.owner = profile
            form.save()

        return redirect("account")
    context = {"form": form, "msg": None}
    return render(request, "users/heart_form.html", context)


import pickle
import numpy as np

# Load the Random Forest CLassifier model
# log_model_file = 'logre_model.pkl'
svc = pickle.load(open("./ml_models/svc_model.pkl", "rb"))

# knn_model_file = 'knn_model.pkl'
knn = pickle.load(open("./ml_models/knn_model.pkl", "rb"))

# rf_model_file = 'rf_model.pkl'
rf = pickle.load(open("./ml_models/rf_model.pkl", "rb"))


def checkHeart(request):
    form = HeartForm()
    msg = ""
    if request.method == "POST":
        form = HeartForm(request.POST)
        if form.is_valid():
            age = form.cleaned_data["age"]
            sex = form.cleaned_data["sex"]
            cp = form.cleaned_data["cp"]
            trestbps = form.cleaned_data["trestbps"]
            chol = form.cleaned_data["chol"]
            fbs = form.cleaned_data["fbs"]
            restecg = form.cleaned_data["restecg"]
            thalach = form.cleaned_data["thalach"]
            exang = form.cleaned_data["exang"]
            oldpeak = form.cleaned_data["oldpeak"]
            slope = form.cleaned_data["slope"]
            ca = form.cleaned_data["ca"]
            thal = form.cleaned_data["thal"]

        data = np.array(
            [
                [
                    age,
                    sex,
                    cp,
                    trestbps,
                    chol,
                    fbs,
                    restecg,
                    thalach,
                    exang,
                    oldpeak,
                    slope,
                    ca,
                    thal,
                ]
            ]
        )

        result = ""
        msg = ""
        accuracy = ""
        if "predict1" in request.POST:
            # for knn
            result = knn.predict(data)

        elif "predict2" in request.POST:
            # for logistic regression
            result = svc.predict(data)

        elif "predict3" in request.POST:
            # for random forest
            result = rf.predict(data)

        # result = model.predict(data)

        if result == 1:
            messages.success(request, "You have Chances of Heart Disease!")
        elif result == 0:
            messages.success(request, "Great! You DON'T chances have Heart Disease.")
        print(msg)
    context = {"form": form, "msg": msg}
    return render(request, "users/heart_form.html", context)

users/templates/users/account.html
{% extends 'main.html' %} {% block content %}

<style>
    table {
        border: 1px solid #ccc;
        border-collapse: collapse;
        margin: 0;
        padding: 0;
        width: 100%;
        table-layout: fixed;
    }

    table caption {
        font-size: 1.5em;
        margin: 0.5em 0 0.75em;
    }

    table tr {
        
        border: 1px solid #ddd;
        padding: 0.35em;
    }

    table th,
    table td {
        padding: 0.725em;
        text-align: left;
    }

    table th {
        background-color: #f8f8f8;
        font-size: 0.85em;
        letter-spacing: 0.2em;
        text-transform: uppercase;
    }

    @media screen and (max-width: 600px) {
        table {
            border: 0;
        }

        table caption {
            font-size: 1.3em;
        }

        table thead {
            border: none;
            clip: rect(0 0 0 0);
            height: 1px;
            margin: -1px;
            overflow: hidden;
            padding: 0;
            position: absolute;
            width: 1px;
        }

        table tr {
            border-bottom: 3px solid #ddd;
            display: block;
            margin-bottom: 0.625em;
        }

        table td {
            border-bottom: 1px solid #ddd;
            display: block;
            font-size: 0.8em;
            text-align: right;
        }

        table td::before {
            /*
          * aria-label has no advantage, it won't be read inside a table
          content: attr(aria-label);
          */
            content: attr(data-label);
            float: left;
            font-weight: bold;
            text-transform: uppercase;
        }

        table td:last-child {
            border-bottom: 0;
        }
       .center {

            display: flex;
            justify-content: center;
            align-items: center;
          
        }
    }
</style>
<!-- Main Section -->
<main class="settingsPage profile my-md">
    <div class="container">
        <div>

        <div class="layout">
            <div class="column column--1of3">
                <div class="card text-center">
                    <div class="card__body dev">
                        <a
                            class="tag tag--pill tag--main settings__btn"
                            href="{% url 'edit-account' %}"
                            ><i class="im im-edit"></i> Edit</a
                        >
                        <img
                            class="avatar avatar--xl dev__avatar"
                            src="{{profile.imageURL}}"
                        />
                        <h2 class="dev__name">{{profile.name}}</h2>
                        <p class="dev__title">{{profile.short_into}}</p>
                        <p class="dev__location">From {{profile.location}}</p>

                        <ul class="dev__social">
                            {% if profile.social_twitter %}
                            <li>
                                <a
                                    title="Twitter"
                                    href="{{profile.social_twitter}}"
                                    target="_blank"
                                    ><i class="im im-twitter"></i
                                ></a>
                            </li>
                            {% endif %} {% if profile.social_linkedin %}
                            <li>
                                <a
                                    title="LinkedIn"
                                    href="{{profile.social_linkedin}}"
                                    target="_blank"
                                    ><i class="im im-linkedin"></i
                                ></a>
                            </li>
                            {% endif %} {% if profile.social_website %}
                            <li>
                                <a
                                    title="Personal Website"
                                    href="{{profile.social_website}}"
                                    target="_blank"
                                    ><i class="im im-globe"></i
                                ></a>
                            </li>
                            {% endif %}
                        </ul>

                    </div>

                </div>
                <div class="text-center">
                    <a
                        class="btn btn--main--outline btn--md my-md"
                        name="genpdf"
                        href="{% url 'report' %}"
                    >Generate Report
                    </a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a class="btn btn--main--outline btn--md my-md" href="{% url 'edit-details' %}">Edit Details</a>
                </div>
                
            </div>
            <div class="column column--2of3">
                <!--  -->
                {% if heart %}
                <!--  -->
                <table>
                    <thead>
                        <th>Features</th>
                        <th>Values</th>
                    </thead>
                    <tbody style=>
                        <tr>
                            <td scope="col">Age</td>
                            <td data-label="Period">{{heart.age}}</td>
                        </tr>
                        <tr>
                            <td scope="col">sex</td>
                            <td data-label="Period">
                                {{heart.get_sex_display}}
                            </td>
                        </tr>
                        <tr>
                            <td scope="col">cp:</td>
                            <td data-label="Period">
                                {{heart.get_cp_display}}
                            </td>
                        </tr>
                        <tr>
                            <td scope="col">trestbps</td>
                            <td data-label="Period">{{heart.trestbps}}</td>
                        </tr>
                        <tr>
                            <td scope="col">chol</td>
                            <td data-label="Period">{{heart.chol}}</td>
                        </tr>
                        <tr>
                            <td scope="col">fbs</td>
                            <td data-label="Period">
                                {{heart.get_fbs_display}}
                            </td>
                        </tr>
                        <tr>
                            <td scope="col">restecg</td>
                            <td data-label="Period">
                                {{heart.get_restecg_display}}
                            </td>
                        </tr>
                        <tr>
                            <td scope="col">thalach</td>
                            <td data-label="Period">{{heart.thalach}}</td>
                        </tr>
                        <tr>
                            <td scope="col">exang</td>
                            <td data-label="Period">
                                {{heart.get_exang_display}}
                            </td>
                        </tr>
                        <tr>
                            <td scope="col">oldpeak</td>
                            <td data-label="Period">{{heart.oldpeak}}</td>
                        </tr>
                        <tr>
                            <td scope="col">slope</td>
                            <td data-label="Period">
                                {{heart.get_slope_display}}
                            </td>
                        </tr>
                        <tr>
                            <td scope="col">ca</td>
                            <td data-label="Period">{{heart.ca}}</td>
                        </tr>
                        <tr>
                            <td scope="col">thal</td>
                            <td data-label="Period">
                                {{heart.get_thal_display}}
                            </td>
                        </tr>


                        <tr>
                            <th scope="col">Prediction Using KNN</th>
                            <th scope="col">
                                {% if heart.result1 == 0 %}
                                <!--  -->
                                <span>Healthy</span>
                                {% elif heart.result1 == 1 %}
                                <span>You Have a chance of Heart Disease</span>

                                {% endif %}
                            </th>
                        </tr>
                        <tr>
                            <th scope="col">Prediction Using SVM Regr</th>
                            <th scope="col">
                                {% if heart.result2 == 0 %}
                                <!--  -->
                                <span>Healthy</span>
                                {% elif heart.result2 == 1 %}
                                <span>You Have a chance of Heart Disease</span>

                                {% endif %}
                            </th>
                        </tr>
                        <tr>
                            <th scope="col">Prediction Using Random Forest</th>
                            <th scope="col">
                                {% if heart.result3 == 0 %}
                                <!--  -->
                                <span>Healthy</span>
                                {% elif heart.result3 == 1 %}
                                <span>You Have a chance of Heart Disease</span>

                                {% endif %}
                            </th>
                        </tr>
                    </tbody>
                </table>
                {% endif %}

                <!--  -->
            </div>
        </div>
    </div>
</main>

{% endblock %}

users/templates/users/heart_form.html
{% extends 'main.html' %} {% block content %}

<!-- Main Section -->
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'account' %}"
                ><i class="im im-angle-left"></i
            ></a>

            {{ msg }}

            <form class="form" method="POST">
                {% csrf_token %} {% for field in form %}

                <div class="form__field">
                    <label for="formInput#text">{{field.label}}</label>
                    {{field}}
                </div>
                {% endfor %}

                <div class="form__field">
                    {% for tag in project.tags.all %}
                    <div
                        class="project-tag tag tag--pill tag--main"
                        data-tag="{{tag.id}}"
                        data-project="{{project.id}}"
                    >
                        {{tag.name}} &#215;
                    </div>
                    {% endfor %}
                </div>
                {% if request.user.is_authenticated %}
                <input
                    class="btn btn--main--outline btn--lg my-md"
                    type="submit"
                    name="predict1"
                    value="Save"
                />
                {% else %}

                <input
                    class="btn btn--main--outline btn--lg my-md"
                    type="submit"
                    name="predict1"
                    value="Predict"
                />

                {% endif %}
                <a
                    class="btn btn--main--outline btn--lg my-md"
                    href="{% url 'account' %}"
                    >Go Back</a
                >
            </form>
        </div>
    </div>
</main>

{% endblock %}

users/templates/users/inbox.html
{% extends 'main.html' %}

{% block content %}
<!-- Main Section -->
<main class="inbox my-xl">
  <div class="content-box">
    <h3 class="inbox__title">New Messages(<span>{{unreadCount}}</span>)</h3>

    <ul class="messages">
      {% for message in messageRequests %}
      {% if message.is_read == False %}
      <li class="message message--unread">
        {% else %}
      <li class="message">
        {% endif %}

        <a href="{% url 'message' message.id %}">
          <span class="message__author">{{message.name}}</span>
          <span class="message__subject">{{message.subject}}</span>
          <span class="message__date">{{message.created}}</span>
        </a>
      </li>
      {% endfor %}
    </ul>
  </div>
</main>

{% endblock content %}

users/templates/users/message.html
{% extends 'main.html' %}


{% block content %}
<!-- Main Section -->
<main class="messagePage my-xl">
  <div class="content-box">
    <div class="message">
      <a class="backButton" href="{% url 'inbox' %}"><i class="im im-angle-left"></i></a>
      <h2 class="message__subject">{{message.subject}}</h4>
        {% if message.sender %}
        <a href="{% url 'user-profile' message.sender.id  %}" class="message__author">{{message.name}}</a>
        {% else %}
        <p class="message__author">{{message.name}}</p>
        {% endif %}
        <p class="message__date">{{message.created}}</p>
        <div class="message__body">{{message.body|linebreaksbr}}</div>
    </div>
  </div>
</main>
{% endblock content %}

users/templates/users/message_form.html
{% extends 'main.html' %}

{% block content %}
<!-- Main Section -->
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'user-profile' recipient.id  %}"><i class="im im-angle-left"></i></a>
            <br>

            <form class="form" method="POST">
                {% csrf_token %}

                {% if request.user.is_authenticated == False %}
                <div class="form__field">
                    <label for="formInput#text">{{form.name.label}}</label>
                    {{form.name}}
                </div>

                <div class="form__field">
                    <label for="formInput#text">{{form.email.label}}</label>
                    {{form.email}}
                </div>
                {% endif %}

                <div class="form__field">
                    <label for="formInput#text">{{form.subject.label}}</label>
                    {{form.subject}}
                </div>

                <div class="form__field">
                    <label for="formInput#text">{{form.body.label}}</label>
                    {{form.body}}
                </div>

                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock content %}